---
alltest:
  - businessTests:
      - case: Get Site BillingConfig Successfully
        http:
          method: GET
          path: /api/billing/siteBillingConfigs/$siteId$?partnerId=10000
          body: {}
        expect:
          responsestate: 200
          responsejsonschemal:
          responseitemcheck: {
            "siteId": $siteId$
          }
          dbcheck: None
          customcheck: {}
      - case: Get Site BillingConfig Failed. Because the siteId is not exist
        http:
          method: GET
          path: /api/billing/siteBillingConfigs/123456?partnerId=10000
          body: {}
        expect:
          responsestate: 404
          responsejsonschemal:
          responseitemcheck: {}
          dbcheck: None
          customcheck: {}
