---
alltest:
- businessTests:
  - case: Enable the restrictedWordsConfig successfully
    http:
      method: POST
      path: /api/global/restrictedWordsConfig:enable?siteId=$siteId$
      body:
    expect:
      responsestate: 200
      responsejsonschemal:
      responseitemcheck: {
         "isEnabled": 'True',
      }
      customcheck: {}