---
alltest:
- businessTests:
  - case: Get restrictedWordsConfig successfully
    http:
      method: GET
      path: /api/global/restrictedWordsConfig?siteid=$siteId$
      head: {
              "Content-Type":'application/json',
              "User-Agent":'Apache-HttpClient/4.5.12 (Java/1.8.0_40)',
              "content-encoding":'gzip'
      }
      body:
      expect:
        responsestate: 200
        responsejsonschemal:
        responseitemcheck: {
          "errorCode":0,
        }
      customcheck: {}
