---
alltest:
- businessTests:
  - case: Disable the restrictedWordsConfig successfully
    http:
      method: POST
      path: /api/global/restrictedWordsConfig:disable?siteId=$siteId$
      body:
    expect:
      responsestate: 200
      responsejsonschemal:
      responseitemcheck: {
         "isEnabled": 'False',
      }
      customcheck: {}