---
alltest:
- businessTests:
  - case: get platform configs
    http:
      method: GET
      path: /centerapi/api/v1/dataservice/platformConfigs?pageIndex=1&pageSize=10
      body: {}
    expect:
      responsestate: 200
      responsejsonschemal:
      responseitemcheck: {}
      customcheck: {}
